### ISSUE TITLE
Just wanted to say thank you for putting this out there.

### ISSUE THREAD

**Issue by bucaran** [miqid/lucid-syntax#2]
:+1:

**Comment by miqid** [comment]
You're most welcome.

I've been thinking about a rework of this package, since I've learnt a bit about the Atom package ecosystem since writing it!

**Comment by bucaran** [comment]
@miqid What do you think about:

* https://github.com/nowk/genericdc or
* https://github.com/robertmeta/nofrils

I love nofrils.
